export const commentsResponse = {
  debug: {
    version: 4,
    "nyt-com-shim": true,
  },
  status: "OK",
  copyright:
    "Copyright (c) 2021 The New York Times Company.  All Rights Reserved.",
  results: {
    callerID: null,
    api_timestamp: "1638889438",
    comments: [
      {
        commentID: 101072791,
        status: "approved",
        commentSequence: 101072791,
        userID: 464875,
        userDisplayName: "true patriot",
        userLocation: "earth",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-ff9acd159afaa60686d6998bac24312a64ec9033a774251c4183f10670a27a6c.jpg",
        commentTitle: "<br\\//>",
        commentBody: "science is so awesome",
        createDate: "1561154463",
        updateDate: "1587240641",
        approveDate: "1561166969",
        recommendations: 26,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072791",
        isAnonymous: false,
      },
      {
        commentID: 101073892,
        status: "approved",
        commentSequence: 101073892,
        userID: 14223544,
        userDisplayName: "Jon",
        userLocation: "Oakland, CA",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "This story is missing a critical detail. How big was it?",
        createDate: "1561161748",
        updateDate: "1561260098",
        approveDate: "1561166964",
        recommendations: 4,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101073892",
        isAnonymous: false,
      },
      {
        commentID: 101072705,
        status: "approved",
        commentSequence: 101072705,
        userID: 74696299,
        userDisplayName: "tom",
        userLocation: "ny state",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Its a giant but the colossal squid is even bigger.",
        createDate: "1561153940",
        updateDate: "1561226739",
        approveDate: "1561166963",
        recommendations: 5,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072705",
        isAnonymous: false,
      },
      {
        commentID: 101072716,
        status: "approved",
        commentSequence: 101072716,
        userID: 65892353,
        userDisplayName: "Frederick Rubie",
        userLocation: "Paris",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "I love grilled squid",
        createDate: "1561154019",
        updateDate: "1561192649",
        approveDate: "1561166961",
        recommendations: 2,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072716",
        isAnonymous: false,
      },
      {
        commentID: 101074138,
        status: "approved",
        commentSequence: 101074138,
        userID: 16205662,
        userDisplayName: "bonemri",
        userLocation: "NJ,USA",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Squid as a species: just trying to survive, NOT destructive or harmful to our planet. Humans as a species: ?",
        createDate: "1561163651",
        updateDate: "1561595996",
        approveDate: "1561163655",
        recommendations: 15,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101074138",
        isAnonymous: false,
      },
      {
        commentID: 101073678,
        status: "approved",
        commentSequence: 101073678,
        userID: 64364208,
        userDisplayName: "6Catmamdo",
        userLocation: "La Crescenta CA.",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "When I taught middle school life science the California squid (Doryteuthis opalescens) was my favorite dissection. My students loved it too and I always showed them amazing videos of the even larger Humbolt squid (Dosidicus gigas), attacking and eating their own that had a camera attached to it. Cephalopods in general and squid in particular make great subjects for instruction as it’s fairly easy to show the connections between the various groups, from Nautilus to cuttlefish to squid and octopus, and they are so foreign to our normal life. Kids can’t wait to explore life so different from what they usually see. Fascinating, thanks for the article. Science is really the hope of our future. \nOh and the scientific name of giant squid is Architeuthis dux.",
        createDate: "1561160138",
        updateDate: "1561596025",
        approveDate: "1561160139",
        recommendations: 33,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101073678",
        isAnonymous: false,
      },
      {
        commentID: 101073072,
        status: "approved",
        commentSequence: 101073072,
        userID: 52210949,
        userDisplayName: "Southamptoner",
        userLocation: "East End",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Really fascinating and happy to learn a bit more about undersea life, thanks.\n\nNot to be churlish,  but I found \"giant squid, the things of our wildest imagination! They’re part of our land, they’re part of our country.” a very odd thing for a scientist to say.  Is a sea creature deep in the Gulf of Mexico really part of our country? And- who cares?  Nature doesn't care about our boundaries, it seemed strange to claim it for the US somehow.",
        createDate: "1561156024",
        updateDate: "1564443673",
        approveDate: "1561156025",
        recommendations: 16,
        replyCount: 2,
        replies: [
          {
            commentID: 101073689,
            status: "approved",
            commentSequence: 101073689,
            userID: 81249932,
            userDisplayName: "io",
            userLocation: "lightning",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Southamptoner I find the comment less nationalistic and more about how activities in the U.S. can impact the habitat and ecosystem -- only 100 miles offshore and near enough to methane flares that one can worry. The comment is about how we are close enough to these creatures to impact them.",
            createDate: "1561160224",
            updateDate: "1617512691",
            approveDate: "1561160225",
            recommendations: 51,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101073072,
            parentUserDisplayName: "Southamptoner",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073689",
            isAnonymous: false,
          },
          {
            commentID: 101079224,
            status: "approved",
            commentSequence: 101079224,
            userID: 57753271,
            userDisplayName: "Jus' Me, NYT",
            userLocation: "Round Rock, TX",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Southamptoner  Actually not in our country, as the border is recognized as twelve miles from the coast.  But I understood what she's saying, it's, like, essentially right here under our noses.  And vessels.",
            createDate: "1561216044",
            updateDate: "1617512700",
            approveDate: "1561216045",
            recommendations: 10,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101073072,
            parentUserDisplayName: "Southamptoner",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101079224",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101073072",
        isAnonymous: false,
      },
      {
        commentID: 101072179,
        status: "approved",
        commentSequence: 101072179,
        userID: 29791194,
        userDisplayName: "jdevi",
        userLocation: "Seattle",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Awesome article.  Fascinating creatures.",
        createDate: "1561151260",
        updateDate: "1617512702",
        approveDate: "1561151890",
        recommendations: 37,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072179",
        isAnonymous: false,
      },
      {
        commentID: 101072034,
        status: "approved",
        commentSequence: 101072034,
        userID: 60614113,
        userDisplayName: "Rob D",
        userLocation: "Rob D   NJ",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Imagine the patience of these scientists.  To wait 7 years between sightings, wow. No wonder their excitement is so great.",
        createDate: "1561150470",
        updateDate: "1617512705",
        approveDate: "1561151824",
        recommendations: 62,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072034",
        isAnonymous: false,
      },
      {
        commentID: 101070582,
        status: "approved",
        commentSequence: 101070582,
        userID: 64842711,
        userDisplayName: "Greg Baumann",
        userLocation: "San JOSE",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "The cutline says the squid attacked. The story says explored. Need to harmonize. I don't see any evidence of the animal deploying its beak, so doesn't seem aggressive enough to warrant attack.",
        createDate: "1561143954",
        updateDate: "1561282519",
        approveDate: "1561151817",
        recommendations: 15,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070582",
        isAnonymous: false,
      },
      {
        commentID: 101070922,
        status: "approved",
        commentSequence: 101070922,
        userID: 78358680,
        userDisplayName: "Benjo",
        userLocation: "Florida",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          '"Is that food?  Can I eat it?  Oh.  No.  That\'s not food."',
        createDate: "1561145346",
        updateDate: "1617867698",
        approveDate: "1561151805",
        recommendations: 36,
        replyCount: 1,
        replies: [
          {
            commentID: 101072798,
            status: "approved",
            commentSequence: 101072798,
            userID: 63661540,
            userDisplayName: "lb",
            userLocation: "san jose, ca",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Benjo  Right?  The scientists were excited.  The squid was disappointed.",
            createDate: "1561154498",
            updateDate: "1617512726",
            approveDate: "1561166989",
            recommendations: 15,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070922,
            parentUserDisplayName: "Benjo",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101072798",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070922",
        isAnonymous: false,
      },
      {
        commentID: 101071638,
        status: "approved",
        commentSequence: 101071638,
        userID: 28571868,
        userDisplayName: "Paul F. Stewart, MD",
        userLocation: "Belfast,Me.",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "I am going to see this in my nightmares !!!",
        createDate: "1561148579",
        updateDate: "1561343901",
        approveDate: "1561151803",
        recommendations: 5,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071638",
        isAnonymous: false,
      },
      {
        commentID: 101070446,
        status: "approved",
        commentSequence: 101070446,
        userID: 76165054,
        userDisplayName: "Joe Hundertmark",
        userLocation: "Mexico",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "woah! the way it moves... that is terrifying!",
        createDate: "1561143379",
        updateDate: "1617512732",
        approveDate: "1561151789",
        recommendations: 15,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070446",
        isAnonymous: false,
      },
      {
        commentID: 101072085,
        status: "approved",
        commentSequence: 101072085,
        userID: 78211779,
        userDisplayName: "Frank J Haydn",
        userLocation: "Washington DC",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-9d7bc41e19b048d4c937b1fd31d4093ee8c371e0de0876743371a437a3722638.jpg",
        commentTitle: "<br\\//>",
        commentBody:
          "I am secretly hoping that one of these creatures becomes so large that it somehow manages to wrap its tentacles around Washington DC one weekend and pull every federal building beneath the surface of the ocean.",
        createDate: "1561150754",
        updateDate: "1612214503",
        approveDate: "1561151786",
        recommendations: 58,
        replyCount: 4,
        replies: [
          {
            commentID: 101073155,
            status: "approved",
            commentSequence: 101073155,
            userID: 51537392,
            userDisplayName: "FWS",
            userLocation: "USA",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody: "@Frank J Haydn\n\nWhat is wrong with you?",
            createDate: "1561156502",
            updateDate: "1561219770",
            approveDate: "1561166967",
            recommendations: 5,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101072085,
            parentUserDisplayName: "Frank J Haydn",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073155",
            isAnonymous: false,
          },
          {
            commentID: 101072365,
            status: "approved",
            commentSequence: 101072365,
            userID: 6709511,
            userDisplayName: "JB",
            userLocation: "Washington",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Frank J Haydn  Just the White House and the Senate leader's office, please.",
            createDate: "1561152156",
            updateDate: "1592179568",
            approveDate: "1561166973",
            recommendations: 22,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101072085,
            parentUserDisplayName: "Frank J Haydn",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101072365",
            isAnonymous: false,
          },
          {
            commentID: 101072929,
            status: "approved",
            commentSequence: 101072929,
            userID: 33112163,
            userDisplayName: "Cadburry",
            userLocation: "Nevada",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Frank J Haydn\nI'd be happy to see republicans fend for themselves, especially commander bone spurs.",
            createDate: "1561155265",
            updateDate: "1561596103",
            approveDate: "1561166993",
            recommendations: 12,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101072085,
            parentUserDisplayName: "Frank J Haydn",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101072929",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072085",
        isAnonymous: false,
      },
      {
        commentID: 101071968,
        status: "approved",
        commentSequence: 101071968,
        userID: 14533576,
        userDisplayName: "JAS",
        userLocation: "Brooklyn, NY",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "finally, some good news :)",
        createDate: "1561150150",
        updateDate: "1561596116",
        approveDate: "1561151781",
        recommendations: 33,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071968",
        isAnonymous: false,
      },
      {
        commentID: 101070837,
        status: "approved",
        commentSequence: 101070837,
        userID: 80101474,
        userDisplayName: "DKM",
        userLocation: "NE Onio",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Very, very cool.\n\nNow, one can only hope for Godzilla, but perhaps emerging from the sea near DC, and taking care of some business there.\n\nOh, please, show the folly of (much of US) man!\n\nAnd then a big ole party.  More cowbell, baby.",
        createDate: "1561144974",
        updateDate: "1561310894",
        approveDate: "1561151780",
        recommendations: 10,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070837",
        isAnonymous: false,
      },
      {
        commentID: 101070359,
        status: "approved",
        commentSequence: 101070359,
        userID: 78216113,
        userDisplayName: "The Buddy",
        userLocation: "Astoria, NY",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "What a fascinating and mysterious animal. Let's get one of these bad boys in a public aquarium.",
        createDate: "1561142977",
        updateDate: "1561388004",
        approveDate: "1561151769",
        recommendations: 1,
        replyCount: 5,
        replies: [
          {
            commentID: 101073926,
            status: "approved",
            commentSequence: 101073926,
            userID: 52465399,
            userDisplayName: "Paul",
            userLocation: "Philadelphia, PA",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody: "@The Buddy\nLet's not.",
            createDate: "1561162048",
            updateDate: "1592179585",
            approveDate: "1561166965",
            recommendations: 40,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070359,
            parentUserDisplayName: "The Buddy",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073926",
            isAnonymous: false,
          },
          {
            commentID: 101074228,
            status: "approved",
            commentSequence: 101074228,
            userID: 67959280,
            userDisplayName: "Bubo",
            userLocation: "Virginia",
            userTitle: "NULL",
            userURL: "NULL",
            picURL:
              "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-51e962b504e77a6f1f1b810fda2b273ccbed4dc3860829daf6133830b40ffa8f.jpg",
            commentTitle: "<br\\//>",
            commentBody:
              "@The Buddy\nNo.  Let them alone.  If scientists want to dissect an already dead individual, that's fine.\nBut let them be. Captivity does no living thing any good.",
            createDate: "1561164246",
            updateDate: "1612214606",
            approveDate: "1561166986",
            recommendations: 35,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070359,
            parentUserDisplayName: "The Buddy",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101074228",
            isAnonymous: false,
          },
          {
            commentID: 101073639,
            status: "approved",
            commentSequence: 101073639,
            userID: 81249932,
            userDisplayName: "io",
            userLocation: "lightning",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@The Buddy Noooo let's stop torturing animals for our entertainment (however well-intended) and instead preserve and protect their habitats and food ecosystem!",
            createDate: "1561159867",
            updateDate: "1592179603",
            approveDate: "1561166994",
            recommendations: 33,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070359,
            parentUserDisplayName: "The Buddy",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073639",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070359",
        isAnonymous: false,
      },
      {
        commentID: 101070793,
        status: "approved",
        commentSequence: 101070793,
        userID: 65886959,
        userDisplayName: "Jon",
        userLocation: "Washington DC",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-4307d02731c6a44dd117cc8749c6b02ef90045ea0a7c5d04e580b4499255b5e8.jpg",
        commentTitle: "<br\\//>",
        commentBody:
          'Squids really are weirder and more "alien" than 99% of sci-fi notions of what aliens may look like.',
        createDate: "1561144819",
        updateDate: "1564074094",
        approveDate: "1561151758",
        recommendations: 28,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070793",
        isAnonymous: false,
      },
      {
        commentID: 101070159,
        status: "approved",
        commentSequence: 101070159,
        userID: 1818725,
        userDisplayName: "Imperato",
        userLocation: "NYC",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Way cool.",
        createDate: "1561142197",
        updateDate: "1561585534",
        approveDate: "1561151756",
        recommendations: 18,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070159",
        isAnonymous: false,
      },
      {
        commentID: 101070169,
        status: "approved",
        commentSequence: 101070169,
        userID: 17149172,
        userDisplayName: "Incanto Blanko",
        userLocation: "Tucson, AZ",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "If you will indulge me . . .\n\nKraken Song\n(The principal predator of the Giant Squid is the Sperm Whale)\n\nCurrents move me.\nI rest, these arms rest,\nThese suckers by which I know thee.\nHow cold you might say, how dark,\nYet I am content.\nCold, dark, only for surface fools\nIf they think of it at all.\n\nThis current that I breathe\nAnd is my being.\nThis cave.\nYou may say I hide after my gorging,\nBut I am only waiting.\nBoth awake and asleep,\nWhich are the same.\n\nI am Seeing.\nYour massive shape looms above,\nWorthy and dangerous.\nCome close so that I may puncture you,\nDrag you into myself\nUntil you must release\nYour poisoned air.\nYour infernal humming,\nBy this too I know thee.\nIt draws me up and out\nInto our fated, fateful dance.\n\nSing to me the wonders of your breath\nBeneath the stars,\nAs I wrap you in my arms,\nRide your surging insouciance.\nI’ll extract from you the price\nFor your invasion,\nTaste your crimson ecstasy—\nYour hunger is your death.\n\nAh, these arms.\nMy limitless reach\nBeyond yours.\nCome. Let me hold you.\nWhen you feel my terror-bite\nIt is too late.\nI love your mass and power\nFor I contain it.\nAnd what is death to me?\nFor I am this ceasless current\nAnd will carry you even when I am gone.\nSurge, unfold, embrace, destroy:\nTry and stop me.\n\nKraken Song ©Fred Weiner Cascabel River Writers 19 May 2018",
        createDate: "1561142237",
        updateDate: "1564074225",
        approveDate: "1561151749",
        recommendations: 29,
        replyCount: 1,
        replies: [
          {
            commentID: 101073944,
            status: "approved",
            commentSequence: 101073944,
            userID: 62424078,
            userDisplayName: "Geoshiva",
            userLocation: "Cooperstown ny",
            userTitle: "NULL",
            userURL: "NULL",
            picURL:
              "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-ff2f18cf16993a084eaaf111dd71c7ad2c77b21a647cdf46c994ad460785e309.jpg",
            commentTitle: "<br\\//>",
            commentBody:
              "@Incanto Blanko\nThank you for sharing this song and poem.",
            createDate: "1561162196",
            updateDate: "1561596222",
            approveDate: "1561178498",
            recommendations: 6,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070169,
            parentUserDisplayName: "Incanto Blanko",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073944",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070169",
        isAnonymous: false,
      },
      {
        commentID: 101070375,
        status: "approved",
        commentSequence: 101070375,
        userID: 42974235,
        userDisplayName: "Julie Zuckman’s",
        userLocation: "New England",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Why is the lead (woman) scientist off to the side? I’m hoping it’s because in the excitement this was the only or best shot taken of the team. Generally the principal investigator should be front and center.",
        createDate: "1561143043",
        updateDate: "1591551113",
        approveDate: "1561151732",
        recommendations: 23,
        replyCount: 2,
        replies: [
          {
            commentID: 101073260,
            status: "approved",
            commentSequence: 101073260,
            userID: 51537392,
            userDisplayName: "FWS",
            userLocation: "USA",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              '@Julie Zuckman’s\n\nYeah, she was sitting front and center, but the photographer said "honey, you and the other broad need to step over to the side so we can place the men in the dominant positions." Of course that is how it all played out.',
            createDate: "1561157195",
            updateDate: "1561565214",
            approveDate: "1561166966",
            recommendations: 12,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070375,
            parentUserDisplayName: "Julie Zuckman’s",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101073260",
            isAnonymous: false,
          },
          {
            commentID: 101076167,
            status: "approved",
            commentSequence: 101076167,
            userID: 40957453,
            userDisplayName: "SmartenUp",
            userLocation: "US",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@Julie Zuckman’s\nOR could it be that having watched the video herself several dozen times--to be sure of what she had--she invited all the others in to get a closer look? Let's not assume anything. \n Why not search up Dr. Widder, e-mail her, and ask about her memory of that event?",
            createDate: "1561182457",
            updateDate: "1561596241",
            approveDate: "1561205330",
            recommendations: 12,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101070375,
            parentUserDisplayName: "Julie Zuckman’s",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101076167",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101070375",
        isAnonymous: false,
      },
      {
        commentID: 101071705,
        status: "approved",
        commentSequence: 101071705,
        userID: 50650074,
        userDisplayName: "Gowan McAvity",
        userLocation: "White Plains",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "As a boy I thrilled when imagining the titanic struggles between Sperm Whales and the mythical Giant Squid, leviathan vs. kraken, with only the telltale scars of foot-wide suckers dotting the flanks of the whales to bear witness to the sheer scale of their battles. Sometimes, my young mind would turn the tables and the whales themselves became prey to the great-grandfather of all giant squids, perhaps wrapping an overly confident young whale on it's first deep dive, in tentacles thicker than me, and dragging the helpless mammal  into cold, dark depths beyond my imaging. Seeing the real thing is even more thrilling to my middle-aged, apparently still childlike mind. What an achievement!  Kudos!",
        createDate: "1561148885",
        updateDate: "1564074330",
        approveDate: "1561151731",
        recommendations: 35,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071705",
        isAnonymous: false,
      },
      {
        commentID: 101071817,
        status: "approved",
        commentSequence: 101071817,
        userID: 61452160,
        userDisplayName: "Susan Fitzwater",
        userLocation: "Ambler, PA",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "There's a short story by H.G. Wells about a giant squid.  Visiting the shores of England way back when.  \n\nGoodness, it was horrifying.  The creature was enormous. Deadly.  Feasting on human beings. \n\nThe more so because Wells (with his natural scientific bent) scrupulously avoided \"purple passages.\"  There are no rhetorical heights or depths in his writing.  He never \"writes up\" anything.  \n\nEverything plain--matter-of-fact.  As if recording (cf. \"The War of the Worlds\") a genuine occurrence--which is just what I thought it the first time I read the piece.  \n\nThe sea.  It surrounds us, doesn't it.  Occupying what? sixty some percent of the earth's surface.  \n\nAnd we cannot LIVE there.  We can work NEAR it or ON and even swim or dive IN it--\n\n--but as a livable environment.  No.  Totally hostile to human life.  \n\nAnd those squids.  And octopuses.  And whales.  And sharks.  How fascinating they are.  Quite deadly, some of them--but fascinating.  Which leads to one more final thought:   \n\nWe're not all stupid in America.  Not yet.  We've haven't ALL gone over to the science-haters--the people that cannot wrap their minds around new ideas, new concepts, new facts.  There's still good SCIENCE going on in the good old USA.  And hey!\n\nMakes me proud of my country.  Just a bit.  \n\nToday's fractious political climate notwithstanding.  And hey!\n\nMore videos of a giant squid would be nice.  \n\nBut I guess those guys think so too.  \n\nMore power to them.",
        createDate: "1561149437",
        updateDate: "1561596318",
        approveDate: "1561151730",
        recommendations: 20,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071817",
        isAnonymous: false,
      },
      {
        commentID: 101071622,
        status: "approved",
        commentSequence: 101071622,
        userID: 68938663,
        userDisplayName: "Marge Keller",
        userLocation: "Midwest",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-5f460d0208a180fd46375901cb2ef8799ef67c1adc7d5b4a85828667ce75876a.jpg",
        commentTitle: "<br\\//>",
        commentBody:
          'I apologize in advance for sounding like a spoiled brat, but I wish this video clip could have been shown in color rather than b/w.  I would have loved to see that "ring of pulsating blue LEDs" against the color of the approaching and attacking juvenile giant squid.\n\nEven so, it is a spectacular and riveting video!\n\nThanks for sharing with the world.',
        createDate: "1561148530",
        updateDate: "1561690837",
        approveDate: "1561148531",
        recommendations: 15,
        replyCount: 1,
        replies: [
          {
            commentID: 101079665,
            status: "approved",
            commentSequence: 101079665,
            userID: 87016466,
            userDisplayName: "Aaron VanAlstine",
            userLocation: "DuPont, WA",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "I believe it was filmed by an infrared camera so by definition it was a color film, just not colors that out eyes register.",
            createDate: "1561218401",
            updateDate: "1561596334",
            approveDate: "1561222971",
            recommendations: 4,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101071622,
            parentUserDisplayName: "Marge Keller",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101079665",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071622",
        isAnonymous: false,
      },
      {
        commentID: 101071103,
        status: "approved",
        commentSequence: 101071103,
        userID: 32039605,
        userDisplayName: "RCJCHC",
        userLocation: "Corvallis OR",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Amazing and wonderful. Keep plastics out of the water stream!",
        createDate: "1561146119",
        updateDate: "1612214468",
        approveDate: "1561146120",
        recommendations: 128,
        replyCount: 1,
        replies: [
          {
            commentID: 101076140,
            status: "approved",
            commentSequence: 101076140,
            userID: 40957453,
            userDisplayName: "SmartenUp",
            userLocation: "US",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@RCJCHC\n\nKeep the fishing vessels out of the water stream.\n\nALL these animals have the right to live their own life, and not be hauled up from the ocean bottom and cooked.\n\nMay I eat YOUR children for dinner?   I thought not...",
            createDate: "1561182009",
            updateDate: "1561690844",
            approveDate: "1561205459",
            recommendations: 8,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101071103,
            parentUserDisplayName: "RCJCHC",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101076140",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101071103",
        isAnonymous: false,
      },
      {
        commentID: 101077406,
        status: "approved",
        commentSequence: 101077406,
        userID: 87068653,
        userDisplayName: "Opinionatedfish",
        userLocation: "Aurora, CO",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-91ead94fedea242895cea83237e0e9836c378d65f7b001ba8db29546997642e1.jpg",
        commentTitle: "<br\\//>",
        commentBody: "It knows that we're here.",
        createDate: "1561205159",
        updateDate: "1587240509",
        approveDate: "1561205373",
        recommendations: 13,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101077406",
        isAnonymous: false,
      },
      {
        commentID: 101076346,
        status: "approved",
        commentSequence: 101076346,
        userID: 81602074,
        userDisplayName: "we Tp",
        userLocation: "oakland",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "A wonderful discovery borne of planning and patience.  I would love to see the video.\n\nI can't help but notice in the photograph that the males have the computer screen pointed to them, and the female director of the program (and designer of the lure) and another female are tucked off to the side, squinting to see from a shallow angle.  Sigh.",
        createDate: "1561186586",
        updateDate: "1629440141",
        approveDate: "1561205320",
        recommendations: 59,
        replyCount: 1,
        replies: [
          {
            commentID: 101077506,
            status: "approved",
            commentSequence: 101077506,
            userID: 18780707,
            userDisplayName: "jharrisonmoore",
            userLocation: "Asheville, North Carolina",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              "@we Tp I noticed that too first thing.  Teeth clenched.",
            createDate: "1561205849",
            updateDate: "1604271547",
            approveDate: "1561222961",
            recommendations: 28,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101076346,
            parentUserDisplayName: "we Tp",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101077506",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101076346",
        isAnonymous: false,
      },
      {
        commentID: 101077240,
        status: "approved",
        commentSequence: 101077240,
        userID: 66533629,
        userDisplayName: "M Davis",
        userLocation: "North Carolina",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "What a delight—sitting here drinking coffee, about to start a busy day, and saw this wonderful article. Congratulations to the team whose labors have provided the world with this dazzling, new information! I may be late for work today, but never mind—what joy it is hear about, and to see this discovery unfold in the midst of all the mayhem and madness that is happening up above on dry land. My thanks to one and all responsible for sharing this momentous event!",
        createDate: "1561203864",
        updateDate: "1633180175",
        approveDate: "1561203865",
        recommendations: 43,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101077240",
        isAnonymous: false,
      },
      {
        commentID: 101075968,
        status: "approved",
        commentSequence: 101075968,
        userID: 12087945,
        userDisplayName: "ROI",
        userLocation: "USA",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Wow.\n\nJust wow!",
        createDate: "1561179327",
        updateDate: "1587240523",
        approveDate: "1561179479",
        recommendations: 36,
        replyCount: 1,
        replies: [
          {
            commentID: 101076990,
            status: "approved",
            commentSequence: 101076990,
            userID: 49331282,
            userDisplayName: "Carol Meise",
            userLocation: "New Hampshire",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody: "@ROImy thoughts exactly!",
            createDate: "1561201283",
            updateDate: "1576979955",
            approveDate: "1561205503",
            recommendations: 9,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101075968,
            parentUserDisplayName: "ROI",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101076990",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075968",
        isAnonymous: false,
      },
      {
        commentID: 101075459,
        status: "approved",
        commentSequence: 101075459,
        userID: 68807301,
        userDisplayName: "Anti-Marx",
        userLocation: "manhattan",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-7428256c726226a63522a153a8b596be8c2d7dce50e1c3d0df0d21b6184b55f9.jpg",
        commentTitle: "<br\\//>",
        commentBody:
          "I imagine that the whip-blow from the tentacle would stun or brain most fish and sea mammals. That wasn't a caress. The squid whipped its tentacle across the light.",
        createDate: "1561173572",
        updateDate: "1592177542",
        approveDate: "1561178513",
        recommendations: 20,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075459",
        isAnonymous: false,
      },
      {
        commentID: 101075381,
        status: "approved",
        commentSequence: 101075381,
        userID: 82804466,
        userDisplayName: "AL",
        userLocation: "Houston, TX",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Calamari for a year!",
        createDate: "1561172852",
        updateDate: "1586914393",
        approveDate: "1561178510",
        recommendations: 18,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075381",
        isAnonymous: false,
      },
      {
        commentID: 101075715,
        status: "approved",
        commentSequence: 101075715,
        userID: 78358680,
        userDisplayName: "Benjo",
        userLocation: "Florida",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          'Giant squids are pretty amazing. Did anyone besides me see the futuristic documentary about what might happen an eon after us humans go extinct?  "Squibbons," a squid-based form of intelligence  which is incredibly agile on trees, ends up being the most likely candidate to replace us. The idea is that squids need a lot of intelligence to operate ten tentacles, change shape and color, and that their intelligence could evolve more if it needed to. Remember we that humans came from a tree-dwelling mammal between a squirrel and a monkey.',
        createDate: "1561176093",
        updateDate: "1623811493",
        approveDate: "1561178503",
        recommendations: 56,
        replyCount: 2,
        replies: [
          {
            commentID: 101075943,
            status: "approved",
            commentSequence: 101075943,
            userID: 78358680,
            userDisplayName: "Benjo",
            userLocation: "Florida",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              '"That we" in my last sentence as opposed to "we that."',
            createDate: "1561178930",
            updateDate: "1593257454",
            approveDate: "1561179480",
            recommendations: 8,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101075715,
            parentUserDisplayName: "Benjo",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101075943",
            isAnonymous: false,
          },
          {
            commentID: 101075991,
            status: "approved",
            commentSequence: 101075991,
            userID: 12087945,
            userDisplayName: "ROI",
            userLocation: "USA",
            userTitle: "NULL",
            userURL: "NULL",
            picURL: null,
            commentTitle: "<br\\//>",
            commentBody:
              'Didn\'t see it, but check out the ending of the 2013 film "Europa Report" about a crew of researchers traveling to that moon...  it\'s magnificent.\n\n<a href="https://www.rottentomatoes.com/m/europa_report" target="_blank">https://www.rottentomatoes.com/m/europa_report</a>/',
            createDate: "1561179591",
            updateDate: "1593257456",
            approveDate: "1561205500",
            recommendations: 9,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101075715,
            parentUserDisplayName: "Benjo",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101075991",
            isAnonymous: false,
          },
        ],
        editorsSelection: true,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075715",
        isAnonymous: false,
      },
      {
        commentID: 101075340,
        status: "approved",
        commentSequence: 101075340,
        userID: 76430734,
        userDisplayName: "A. Stanton",
        userLocation: "Dallas, TX",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-5c75a91ebce57abbf90534cfebcdba854b6abd3e25daa155a6e3780516bbbfad.jpg",
        commentTitle: "<br\\//>",
        commentBody:
          "So, what do Huckabee Sanders, Kellyanne Conway and giant squids have in common?\n\nLike them, giant squids aren't known known for being partial to holding press briefings.\n\nI can easily see one being appointed as Trump's next White House Press Secretary.\n\nProvided,of course, that  he or she is able to get a top-level security clearance.",
        createDate: "1561172536",
        updateDate: "1587240584",
        approveDate: "1561178496",
        recommendations: 14,
        replyCount: 1,
        replies: [
          {
            commentID: 101077307,
            status: "approved",
            commentSequence: 101077307,
            userID: 76430734,
            userDisplayName: "A. Stanton",
            userLocation: "Dallas, TX",
            userTitle: "NULL",
            userURL: "NULL",
            picURL:
              "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-5c75a91ebce57abbf90534cfebcdba854b6abd3e25daa155a6e3780516bbbfad.jpg",
            commentTitle: "<br\\//>",
            commentBody:
              "Like them, giant squids aren't  known for being partial to holding press briefings.",
            createDate: "1561204507",
            updateDate: "1561595736",
            approveDate: "1561205466",
            recommendations: 4,
            replyCount: 0,
            replies: [],
            editorsSelection: false,
            parentID: 101075340,
            parentUserDisplayName: "A. Stanton",
            depth: 2,
            commentType: "userReply",
            trusted: 0,
            recommendedFlag: 0,
            permID: "101077307",
            isAnonymous: false,
          },
        ],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075340",
        isAnonymous: false,
      },
      {
        commentID: 101075789,
        status: "approved",
        commentSequence: 101075789,
        userID: 59460227,
        userDisplayName: "David Doney",
        userLocation: "I.O.U.S.A.",
        userTitle: "NULL",
        userURL: "NULL",
        picURL:
          "https://s3.amazonaws.com/pimage.timespeople.nytimes.com/avatars/cropped-4cc24fcf78c1625e03dc6e4a29a1c330c0b2189d5b71fafaf3f8067c0f5e996f.jpg",
        commentTitle: "<br\\//>",
        commentBody: "A forty-foot squid!   That's a lot of calamari!",
        createDate: "1561176857",
        updateDate: "1561659914",
        approveDate: "1561178482",
        recommendations: 6,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075789",
        isAnonymous: false,
      },
      {
        commentID: 101072816,
        status: "approved",
        commentSequence: 101072816,
        userID: 66969374,
        userDisplayName: "Bill",
        userLocation: "Denver",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "So, I'm thinking Calamari tonight.",
        createDate: "1561154632",
        updateDate: "1561595741",
        approveDate: "1561178480",
        recommendations: 6,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072816",
        isAnonymous: false,
      },
      {
        commentID: 101075042,
        status: "approved",
        commentSequence: 101075042,
        userID: 60752282,
        userDisplayName: "Castanea Sativa",
        userLocation: "USA",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Jules Verne and Captain Nemo are delighted. Herman Melville also since sperm whales feast on giant squids.",
        createDate: "1561169878",
        updateDate: "1561595745",
        approveDate: "1561178478",
        recommendations: 20,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075042",
        isAnonymous: false,
      },
      {
        commentID: 101075478,
        status: "approved",
        commentSequence: 101075478,
        userID: 59564464,
        userDisplayName: "Tasha",
        userLocation: "Oregon",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "What a wonderful article. The excitement of the researchers made me smile, and given how many sociopathic and greedy people there are out there who are eager to destroy the earth for their own benefit, I really need the stories about those who are the polar opposite. Like these researchers, helping us get a better understanding of the wondrous creatures that inhabit this earth - you know, before we manage to kill them off.",
        createDate: "1561173751",
        updateDate: "1621731599",
        approveDate: "1561178475",
        recommendations: 67,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075478",
        isAnonymous: false,
      },
      {
        commentID: 101075810,
        status: "approved",
        commentSequence: 101075810,
        userID: 69494728,
        userDisplayName: "Dave",
        userLocation: "Sacramento",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Great. Now even octopi are doing selfies?",
        createDate: "1561177087",
        updateDate: "1600709815",
        approveDate: "1561178469",
        recommendations: 14,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101075810",
        isAnonymous: false,
      },
      {
        commentID: 101074548,
        status: "approved",
        commentSequence: 101074548,
        userID: 47231546,
        userDisplayName: "Hal S",
        userLocation: "Earth",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Congratulations to Dr. Widder for her now proven innovative technique and the crew of the Point Sur for making this all possible!",
        createDate: "1561166234",
        updateDate: "1612214563",
        approveDate: "1561167005",
        recommendations: 53,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101074548",
        isAnonymous: false,
      },
      {
        commentID: 101072977,
        status: "approved",
        commentSequence: 101072977,
        userID: 65928700,
        userDisplayName: "richard wiesner",
        userLocation: "oregon",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "Thank you for the video with a great shot of the tentacle. That definitely fulfilled my cephalopod fix for the day. Don't wait seven years for the next view. The science section is always my first stop when I read the paper, for reasons of mental clarity.",
        createDate: "1561155488",
        updateDate: "1562109817",
        approveDate: "1561167003",
        recommendations: 43,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072977",
        isAnonymous: false,
      },
      {
        commentID: 101072586,
        status: "approved",
        commentSequence: 101072586,
        userID: 59545008,
        userDisplayName: "New World",
        userLocation: "NYC",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody: "Fried calamari for the whole school.",
        createDate: "1561153253",
        updateDate: "1564443506",
        approveDate: "1561166999",
        recommendations: 5,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072586",
        isAnonymous: false,
      },
      {
        commentID: 101073530,
        status: "approved",
        commentSequence: 101073530,
        userID: 77827474,
        userDisplayName: "Illuminati Reptilian Overlord #14",
        userLocation: "UFO in the hollow earth",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "The senate will be briefed. Last week, UFOs; this week, leviathans of the deep.",
        createDate: "1561159122",
        updateDate: "1587240620",
        approveDate: "1561166997",
        recommendations: 11,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101073530",
        isAnonymous: false,
      },
      {
        commentID: 101072996,
        status: "approved",
        commentSequence: 101072996,
        userID: 62523154,
        userDisplayName: "@lawyerneering",
        userLocation: "Houston",
        userTitle: "NULL",
        userURL: "NULL",
        picURL: null,
        commentTitle: "<br\\//>",
        commentBody:
          "We’re gonna need a bigger fryer! (Just kidding. That’s a magnificent creature and great story).",
        createDate: "1561155608",
        updateDate: "1561595937",
        approveDate: "1561166992",
        recommendations: 12,
        replyCount: 0,
        replies: [],
        editorsSelection: false,
        parentID: null,
        parentUserDisplayName: null,
        depth: 1,
        commentType: "comment",
        trusted: 0,
        recommendedFlag: 0,
        permID: "101072996",
        isAnonymous: false,
      },
    ],
    depthLimit: 2,
    filter: "",
    page: 5,
    replyLimit: 3,
    sort: "",
    totalCommentsFound: 102,
    totalCommentsReturned: 35,
    totalEditorsSelectionFound: 1,
    totalEditorsSelectionReturned: 1,
    totalParentCommentsFound: 69,
    totalParentCommentsReturned: 25,
    totalRecommendationsFound: 101,
    totalRecommendationsReturned: 35,
    totalReplyCommentsFound: 33,
    totalReplyCommentsReturned: 10,
    totalReporterReplyCommentsFound: 0,
    totalReporterReplyCommentsReturned: 0,
    userData: {
      userID: 0,
      login: null,
      email: "",
      displayName: "",
      url: "",
      title: "",
      location: "",
      times_people: 0,
      sharing: 0,
      labels: [],
    },
  },
  errorDetails: "",
};
